name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          echo "Setting up environment"
          # Add setup cmd

      - name: Run tests
        run: |
          echo "Running tests"
          # Add test cmd

