name: Lost-in-Faubourg CI/CD

on:
  push:
    paths:
      - "map-application/**"
  pull_request:
    branches:
      - main
    paths:
      - "map-application/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
          cache: "npm"

      - name: Install dependencies
        run: cd map-application && npm install

      - name: Run Linter
        run: cd map-application && npm run lint

      - name: Run Test Suite
        run: cd map-application && npm test

      - name: Build the Project
        run: cd map-application && npx expo export --platform web
