name: Lost-in-faubourg CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Test Suite with Coverage and Generate JUnit Report
        env:
          CI: true
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ always() }}
        uses: codecov/test-results-action@v1
        with:
          file: ./test-results/junit.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Set Environment Variables
        run: echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> $GITHUB_ENV

      - name: Build the Project (iOS)
        run: npx expo export --platform ios

      - name: Build the Project (Android)
        run: npx expo export --platform android
